#!/bin/sh
set -e
if [ -f /etc/os-release ]; then
  . /etc/os-release
  case $ID in
    ubuntu)
      case $VERSION_ID in
        18.04)
          echo -n 'dnsutils vim neofetch zsh tmux azure-cli'
        ;;
        20.04)
	  # When https://github.com/Azure/azure-cli/issues/13081 gets resolved,
          # I can add azure-cli to my 20.04 package list
          echo -n 'dnsutils vim neofetch zsh tmux azure-cli'
        ;;
        *)
          >&2 echo "Unsupported version of $NAME: $VERSION_ID"
          exit 1;
        ;;
      esac
    ;;
    arch)
      echo -n 'bind-tools tmux neofetch zsh'
    ;;
    *)
      >&2 echo "Unsupported OS: $NAME"
      exit 1
    ;;
  esac
else
  >&2 echo 'Failed to sniff environment'
  exit 1;
fi
echo
