name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: alpine:3
          - image: archlinux
          - image: debian:9
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: debian:10
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: elementary/docker:stable
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: kalilinux/kali-rolling
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:18.04
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:20.04
            env:
              DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Run non-interactive install
        env:
          branch: ${GITHUB_REF#refs/head/}}
        run: ./tools/install.sh --no-interactive

