name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: alpine:3
          - image: archlinux
          - image: debian:9
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: debian:10
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: elementary/docker:stable
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: kalilinux/kali-rolling
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:18.04
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:20.04
            env:
              DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Install CI Tools
        run: ./tools/private/install-ci-tools.sh
      - name: Set Installation Environment Variables
        run: echo "::set-env name=branch::$(git -C $GITHUB_WORKSPACE rev-parse --abbrev-ref HEAD)"
      - name: Run non-interactive install
        run: curl -fsSL "https://raw.githubusercontent.com/lannuttia/dotfiles/$branch/tools/install.sh" | sh -s -- --no-interactive

